#!/bin/bash
mkdir bin
cd bin
ls
g++ -c -std=c++14 -DCI -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -Werror -Wno-unused-variable -fext-numeric-literals -I../src ../src/*.*
g++ *.o -o teksto
